#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@File    :   contract_terms_search.py
@Time    :   2024/05/29 14:10:37
@Author  :   Xin HUANG 
@Version :   1.0
@Contact :   xin.huang@capgemini.com
'''

# here put the import lib
import streamlit as st
import pandas as pd
import numpy as np
# import torch
# import spacy
from sentence_transformers import SentenceTransformer, util

def header_app():
    
    st.image("TASC-orange-horizontal-logo.png",width=500,)
    with st.expander("ℹ️ - About this app", expanded=True):

        st.write(
        """  
-   The generated contracts or terms must be reviewed by professional legal personnel before they can be used. This app can help you quickly find contracts and terms that have been reviewed.
-   The *Contract Terms Search* app is used to search the company's contract database for contracts and terms that are most similar to the contracts or terms generated by the GenAI model. 
-   The Top-3 most similar candidates are displayed in the results along with their cosine similarity to the generated terms.
-   Our app is based on the model Gemini 1.5 from Google Vertex AI. 
	    """
    )
    st.header("Contract Terms Search",divider='rainbow')     
header_app()

model = SentenceTransformer('all-MiniLM-L6-v2')

ques = st.text_area('Text')
st.markdown("""### Example of generated clause:(Select a text, copy and paste it into the text box above)
* This Agreement shall be governed by and construed in accordance with the laws of the State of [State Name], without regard to its conflict of laws principles. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded.
* This Agreement shall be automatically renewed for an additional [Number]-year term (the “Renewal Term”) upon the expiration of the Initial Term, unless either Party provides written notice to the other Party of its intention not to renew at least [Number] days prior to the expiration of the Initial Term. 
* This Contract Clause of Insurance ("Clause") forms part of the Agreement between [Name of Insured] ("Insured") and [Name of Insurer] ("Insurer").
* Right to Terminate
(a) The [Government/Company] may terminate this Contract, in whole or in part, at any time for its convenience. The termination will be effective upon delivery to the [Contractor/Supplier] of a written notice of termination.
(b) The [Government/Company] shall not be liable for any costs or damages incurred by the [Contractor/Supplier] as a result of the termination, except as provided in this Clause.
""")

embeddings1 = model.encode(ques, convert_to_tensor=True)
ques_list = list()
ques_list.append("This Agreement is governed by English law. 22.2 The Parties submit to the non-exclusive jurisdiction of the courts of England and Wales. This Agreement shall come into force on the date given at the beginning of this Agreement. ")
ques_list.append("This Agreement shall be governed by and construed in accordance with the laws of the State of Colorado excluding its choice of law provisions. The United Nations Convention on Contracts for the International Sale of Goods (CISG) is specifically excluded and shall not be applicable to any transaction contemplated herein.")
ques_list.append("Disputes and Applicable Law This Agreement (including any dispute hereunder) and the documents to be entered into pursuant to it, save as expressly otherwise provided therein, will be governed by and construed in accordance with the Laws of the Netherlands.")
ques_list.append("This Agreement shall be governed in all respects, including as to validity, interpretation and effect, by the Laws of the State of Illinois, without giving effect to its principles or rules of conflict of laws, to the extent such principles or rules are not mandatorily applicable by statute and would permit or require the application of the Laws of another jurisdiction. Each of the Parties hereto submits to the jurisdiction of any state or federal court sitting in Lake County, Illinois, in any action or proceeding arising out of or relating to this Agreement, agrees to bring all claims under any theory of liability in respect of such action or proceeding exclusively in any such court and agrees not to bring any action or proceeding arising out of or relating to this Agreement in any other court. Each of the Parties hereto waives any defense of inconvenient forum to the maintenance of any action or proceeding so brought and waives any bond, surety or other security that might be required of any other party with respect thereto. Each Party hereto agrees that service of summons and complaint or any other process that might be served in any action or proceeding may be made on such Party by sending or delivering a copy of the process to the Party to be served at the address of the Party and in the manner provided for the giving of notices in Section 10.5. Nothing in this Section 10.8, however, shall affect the right of any Party to serve legal process in any other manner permitted by Law. Each Party hereto agrees that a final, non-appealable judgment in any action or proceeding so brought shall be conclusive and may be enforced by suit on the judgment or in any other manner provided by Law.")
ques_list.append("SIGNED by ) ) (name), ) a duly authorised signatory of ) (signature) SHBV (HONG KONG) LTD ) SIGNED by ) ) (name), ) a duly authorised signatory of ) (signature) WASTE2ENERGY GROUP HOLDINGS PLC )")
ques_list.append("The initial term of this Agreement shall be for a period of one (1) year from the Effective Date unless sooner terminated pursuant to the termination provisions herein. Thereafter, this Agreement automatically renews for successive terms of one (1) year.")
ques_list.append("Insurance Philips shall fully comply with the terms of the Quality Agreement regarding its obligations and responsibilities with respect to maintaining the required level of insurance. 18.13 Further Assurances Each Party shall at its own costs and expenses from time to time execute such documents and perform such acts and things as the other Party may reasonably require to give the other Party the full benefit of this Agreement.")
# ques_list.append("")
ans = ['' for i in range(len(ques_list))]

print('questions list length:', len(ques_list))

embeddings2 = model.encode(ques_list, convert_to_tensor=True)
cosine_scores = util.cos_sim(embeddings1, embeddings2)
# print(cosine_scores)
# sorted, indices = torch.sort(cosine_scores)
# print(sorted)
# print(indices)

similarity_df = pd.DataFrame({"Questions":ques_list,"Similarity":cosine_scores[0].tolist(), "Answers":ans})
similarity_df.sort_values('Similarity',ascending = False,inplace = True )


if st.button('submit'):
    st.write("Similar text (Top-3)")
    st.dataframe(similarity_df.head(3))
    print('end')
